### ISSUE TITLE
Missing dependency on dconf in this project

### ISSUE THREAD

**Issue by Rudd-O** [QubesOS/qubes-gui-agent-linux#2] opened 2015-10-10 07:38 UTC
The qubes show hide nm applet shell script fails to properly hide the NetworkManager icon if dconf is not present, due to gsettings falling back to using the memory backend whose changes aren't seen at all by the NetworkManager applet.

**Comment by marmarek** [comment] 2015-10-10 12:47
Duplicate of QubesOS/qubes-issues#1299

And BTW, please use qubes-issues repository.

**Closed by marmarek** 2015-10-10 12:47 UTC
