### ISSUE TITLE
Missing dependency on `which` package in this project

### ISSUE THREAD

**Issue by Rudd-O** [QubesOS/qubes-gui-agent-linux#1] opened 2015-10-10 07:27 UTC
Because which as a command is not present in this package as a dependency, the minimal Fedora template fails to execute /usr/lib/qubes/show-hide*.sh -- causing the NM applet icon to remain on the taskbar.

Please fix.

**Comment by marmarek** [comment] 2015-10-10 12:49
Duplicate of QubesOS/qubes-issues#1299, thanks for pointing out what packages are missing.

**Closed by marmarek** 2015-10-10 12:49 UTC
